### ISSUE TITLE
labels should be int in train.py, line 45

### ISSUE THREAD

**Issue by wanyao1992** [Diego999/pyGAT#1]
Dear authors,

Thank you for sharing you code. When I run the source code, I encountered the following problem. 

Traceback (most recent call last):
  File "train.py", line 45, in <module>
    model = GAT(nfeat=features.shape[1], nhid=args.hidden, nclass=labels.max() + 1, dropout=args.dropout, nheads=args.nb_heads, alpha=args.alpha)
  File "/home/wanyao/www/Dropbox/ghproj/pyGAT/models.py", line 16, in __init__
    self.out_att = GraphAttentionLayer(nhid * nheads, nclass, dropout=dropout, alpha=alpha, concat=False)
  File "/home/wanyao/www/Dropbox/ghproj/pyGAT/layers.py", line 22, in __init__
    self.a = nn.Parameter(nn.init.xavier_uniform(torch.Tensor(2*out_features, 1).type(torch.cuda.FloatTensor if torch.cuda.is_available() else torch.FloatTensor), gain=np.sqrt(2.0)), requires_grad=True)
TypeError: new() received an invalid combination of arguments - got (Variable, int), but expected one of:
 * (int device)
 * (tuple of ints size, int device)
      didn't match because some of the arguments have invalid types: (Variable, int)
 * (torch.Storage storage)
 * (Tensor other)
 * (object data, int device)
      didn't match because some of the arguments have invalid types: (Variable, int)

This is caused by that, in line 45 of train.py, labels should be int type, not torch.LongTensor.
model = GAT(nfeat=features.shape[1], nhid=args.hidden, nclass=labels.max() + 1, dropout=args.dropout, nheads=args.nb_heads, alpha=args.alpha)

After I modified "labels.max()" to be "int(labels.max())", the problem is solved.

**Comment by diegoantognini** [comment]
Hi wanyao1992,

I'm not one of the authors despite I would like ;)

For your error, what version of pytorch/numpy do you use ? Maybe it's a matter of auto-cast

**Comment by diegoantognini** [comment]
(I fixed it just in case in  https://github.com/Diego999/pyGAT/commit/9f6afbe25a2389572d34365f90b63fae9b4bc481)

**Comment by wanyao1992** [comment]
Hi Diego,

Acutually, I use the Python 3.6.4, pytorch 0.4 and numpy 1.14.1.

**Comment by diegoantognini** [comment]
Hum I'm using python 3.5.2 and numpy 1.13.3. I guess this should be the difference. Anyway, it's fixed :)
