### ISSUE TITLE
Im having trouble understanding these lines

### ISSUE THREAD

**Issue by derek-saal** [Diego999/pyGAT#10]
https://github.com/Diego999/pyGAT/blob/808e0ffceb464a3a07893733f62073b47429a727/layers.py#L31-L32

It seems that these 2 lines are implementing the argument of LeakyReLU in Equation (3) from the [paper page 3](https://arxiv.org/pdf/1710.10903.pdf#page=3). 

But I don't know how it works. Can you explain it?

Also, I'm getting memory issues on these two lines when trying with other data.

Thanks,
@derek-saal

**Comment by diegoantognini** [comment]
Hi,

Sorry for the late answer. Yes that's the implementation of Eq 3. It is just the naive computation of the cartesian product. To convince yourself, try to "debug" these line with matrices such that [[[1,1,1],[2,2,2], [3,3,3]]] and you will see that you what you will have with ```h.repeat(1, N).view(N * N, -1)``` and ```h.repeat(N, 1)```. In the original tensorflow implementation, they use a FFN. Have a look on the branch similar_impl_tensorflow.
