### ISSUE TITLE
Citeseer data set accuracy

### ISSUE THREAD

**Issue by xuhaiyun42** [Diego999/pyGAT#14]
Hello!I used the GAT network to run the citeseer database, but the accuracy could not reach 72.5, only 70.3. How did you set the parameters to run so high?

**Comment by diegoantognini** [comment]
I didn't run it on citeseer. I guess you should try different configuration of GAT & parameters

**Comment by tonyandsunny** [comment]
Hello!  I only have 0.703 on citeseer dataset. But the citeseer parameters in this paper are the same as those in cora. Can we change these parameters to run the experiment?

**Comment by yufengwhy** [comment]
also 0.703 on citeseer dataset... Can anyone obtain the results 0.725 as the paper, using this code of pyGAT?

**Comment by starsky68** [comment]
@yufengwhy ,  @tonyandsunny ,  @xuhaiyun42  Hello, can you help me? Can you provide me with the citeseer and pubmed data sets (.cites and .content) for you to use? thank you very much.

**Comment by Ldoun** [comment]
https://github.com/PetarV-/GAT/issues/14
based on this repo issue, I changed EarlyStopping code to monitor acc. and I got acc of 0.714 on test set
