### ISSUE TITLE
Batchwise Training

### ISSUE THREAD

**Issue by bangann** [Diego999/pyGAT#15]
Hi,

Nice job and thanks for sharing!  I am doing the graph classification problem (different graphs with the same #nodes and #features ). I'm wondering can I use GAT to do the graph classification? Is that means different graphs should share the same weights matrix W? And how can I modify the model for batch-wise training?

Hope for your suggestions!

**Comment by tbright17** [comment]
Have the same question here.

**Comment by vijaydwivedi75** [comment]
Hi @Andy5250, any solution on the batchwise training?

**Comment by swg209** [comment]
@vijaydwivedi75 @Diego999 @Andy5250   Hell.o. Is there any solution to the batchwise training?
