### ISSUE TITLE
Is adj normalization essential?

### ISSUE THREAD

**Issue by bangann** [Diego999/pyGAT#17]
Hi Diego,

Thank you so much for sharing your code! But I am confused with adj matrix. 
In layers.py "attention = torch.where(adj > 0, e, zero_vec)", it seems that adj(normalized) just used as an adjacency matrix which shows whether there is an edge between two nodes. If it is true, why it should be normalized? From my understanding, adj(normalized)>0 and adj(unnormalized)>0 are the same.

Hope for your reply.
Thx!

**Comment by diegoantognini** [comment]
Hi @Andy5250 

I think this is how it's done in the original implementation. But if both are the same, shouldn't change anything.

Best,

**Comment by bousejin** [comment]
Hi Diego,

Thank you so much for the code! In layers.py this line (edge = adj.nonzero().t()) says AttributeError: 'Tensor' object has no attribute 'sparse'. How can I get rid of it?

**Comment by diegoantognini** [comment]
Did you check your version of pytorch ?

**Comment by bousejin** [comment]
It is '1.0.0'.

**Comment by diegoantognini** [comment]
Ok I think the API might have changed since. I don't have time to fix it but a PR is welcome ;-)
