### ISSUE TITLE
Any particular reason for the parameter initialization you used?

### ISSUE THREAD

**Issue by mufeili** [Diego999/pyGAT#18]
Hi, thank you for the great work! 

I'm curious about way you initialized the model parameters. In the official TensorFlow implementation, if I understand correctly, the authors used the default parameter initialization of `tf.layers.conv1d`, which according to [the source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variable_scope.py#L292) uses `glorot_uniform_initializer` with a default `gain=1.0` as in [the source code](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/ops/init_ops.py#L1120).

In your implementation, you used `glorot_uniform_initializer` with `gain=1.414` for `GraphAttentionLayer` as in [L21](https://github.com/Diego999/pyGAT/blob/3301fd68cbf349925d7458d9d47766e48021cf78/layers.py#L21) and `glorot_normal_initializer` with `gain=1.414` for `SpGraphAttentionLayer` as in [L90](https://github.com/Diego999/pyGAT/blob/3301fd68cbf349925d7458d9d47766e48021cf78/layers.py#L90). Is there a particular reason for doing so? Thank you.

**Comment by diegoantognini** [comment]
Hi,

It shouldn't change that much. There are theoretical reason why gain should be 2^0.5 when using specific activation function but in practice you can use whatever you want.

Cheers,
