### ISSUE TITLE
Only two layer are implemented

### ISSUE THREAD

**Issue by SayHelloToWorld** [Diego999/pyGAT#19]
I see you only implemented two layer's GAT, the accuracy of your model will lower than the official implementation, right? I want to do my experiment based on your code, and can you give me some advice on the relationships between the number of layers and the final accuracy or F1 score?

**Comment by diegoantognini** [comment]
Hey,

Unfortunately this depends a lot of the task and the data. Therefore you will need to experiment yourself. Sorry
