### ISSUE TITLE
out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by chirstinaFan** [Diego999/pyGAT#2]
hi，when I run the code in GPU,it is out of memory .
can you see this problems?

**Comment by diegoantognini** [comment]
Hi,

The attention function in the master branch is quiet memory eager. If you
don’t have enough GRAM, switch to the other branch where the attention
function is memory friendly but the performances will be less good.

Best,

-- 
Diego Antognini

From: chirstinaFan <notifications@github.com> <notifications@github.com>
Reply: Diego999/pyGAT
<reply@reply.github.com>
<reply@reply.github.com>
Date: 12 April 2018 at 07:54:38
To: Diego999/pyGAT <pygat@noreply.github.com> <pygat@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [Diego999/pyGAT] out of memory at
/pytorch/torch/lib/THC/generic/THCStorage.cu:58 (#2)

hi，when I run the code in GPU,it is out of memory .

**Comment by chirstinaFan** [comment]
OK.thank you!

**Comment by abhigoku10** [comment]
@Diego999  what is the min memory GRAM requirement to ru n the current repo
