### ISSUE TITLE
Could you please give me a guide on finding other datasets in your paper

### ISSUE THREAD

**Issue by hehaodele** [Diego999/pyGAT#21]
Hi, Diego

Your code is very useful and easy to use. I want to reproduce its performance on the other datasets such as Citeseer. Could you mind tell me how to download and process those datasets?

Thanks,
Hao

**Comment by vijaydwivedi75** [comment]
any help @hehaodele . apparently I have the same question.

Did you get to download in the similar format which this repo has?

**Comment by abhigoku10** [comment]
@hehaodele @vijaydwivedi75  where you able to solve this issue ??
