### ISSUE TITLE
Node Classification with Multiple Graphs

### ISSUE THREAD

**Issue by ghost** [Diego999/pyGAT#28]
Hi, I am trying to do an implementation which requires to input multiple graphs for node classification task. All the examples I've seen so far was for graph classification for this case. Although I've seen building block diagonal adjacency matrix, I'm not sure if it is for graph classification or node. Also I didn't understand whether should I create a block diagonal matrix with feature matrix and labels too or not.

Let's suppose I have 20 different graphs(with different number of nodes, edges, features). And each node of every graph is labeled.
All the nodes in first 10 graphs are for training, all the nodes of the next 5 graphs are for val, and all the nodes of last 5 graphs are for test. What I'm trying to do is predicting labels of the nodes for the graphs in test-set. How can I input multiple graphs into GAT(or any other GNN) with these conditions for node classification task(not for graph classification).? If the solution is block diagonal adj. matrix, should I do the same for labels and feature matrix too?

**Comment by Sisi0518** [comment]
Why you closed this issue? Have you found a solution?

**Comment by tanjia123456** [comment]
hello, I also meet such problem. Do you know how to solve it? I have confused for one month
