### ISSUE TITLE
normalize_adj is confusing

### ISSUE THREAD

**Issue by chenfei-wu** [Diego999/pyGAT#3]
As explained in https://en.wikipedia.org/wiki/Laplacian_matrix, Symmetric normalized Laplacian is I-D^(-1/2)AD^(-1/2). However, the function normalize_adj() in utils.py seems to only perform D^(-1/2)AD^(-1/2).

**Comment by diegoantognini** [comment]
Hi,

Thank you for your remark. Wikipedia is indeed right however, in our case, we are working with A_tilda 
 (= A + I) and D_tilda and therefore, the expression is correct if you follow the derivation of https://arxiv.org/pdf/1609.02907.pdf .

Are you convinced ?

**Comment by chenfei-wu** [comment]
Yes. Thank you very much for your reply.
