### ISSUE TITLE
How to run pyGAT in parallel?

### ISSUE THREAD

**Issue by fuyw** [Diego999/pyGAT#5]
Thanks Diego for sharing the code.

I have a question about run the code in parallel, since the multi-head attention mechanism should be able run in parallel efficiently.

But I can't figure out how to make it?

Can anyone help, many thanks.

**Comment by diegoantognini** [comment]
Hi,

How did you measure this ? Anyway this should be automatic as the graph is built and then the computation is run

**Comment by diegoantognini** [comment]
Did you figure it out ?

**Comment by fuyw** [comment]
Hi Diego, many thanks for your reply :)

Apologize for not describing my problem clearly. I want to run `pyGat.py` with multiple gpus, like: `model = torch.nn.DataParallel(model, device_ids=[1, 2, 3, 4])`.

Since adding `model = DataParallel(model, device_ids=[1,2,3,4])` directly will split inputs into four times smaller size. In `cora` dataset, we'll have `feature.shape = (677, 2708)` and `adj.shape=(677, 1433)` due to `2708 / 4 = 677`. 

Then `attention = torch.where(adj > 0, e, zero_vec)` raise an error because of size conflict where `e.shape = (677, 677)`.

To solve above problem, I extend the input dimension with `adj = adj.unsqueeze(0)` and `features = features.unsqueeze(0)` in `train.py`.  And modify some codes related to the shapes in `layers.py` , `models.py` and `training.py`, which can be found [here](https://github.com/fuyw/pyGAT).

Now I can run `train.py` as usual, but still only one gpu is used.

So I am confused how to use multiple gpus to run `pyGAT`.

**Comment by diegoantognini** [comment]
Hi fuyw,

Unfortunately I've never experimented to run any code on multiple GPUs therefore I cannot help you. However, if you find a solution, it would be nice to share it here ;-)

**Comment by Serendipity-LC** [comment]
> Hi Diego, many thanks for your reply :)
> 
> Apologize for not describing my problem clearly. I want to run `pyGat.py` with multiple gpus, like: `model = torch.nn.DataParallel(model, device_ids=[1, 2, 3, 4])`.
> 
> Since adding `model = DataParallel(model, device_ids=[1,2,3,4])` directly will split inputs into four times smaller size. In `cora` dataset, we'll have `feature.shape = (677, 2708)` and `adj.shape=(677, 1433)` due to `2708 / 4 = 677`.
> 
> Then `attention = torch.where(adj > 0, e, zero_vec)` raise an error because of size conflict where `e.shape = (677, 677)`.
> 
> To solve above problem, I extend the input dimension with `adj = adj.unsqueeze(0)` and `features = features.unsqueeze(0)` in `train.py`. And modify some codes related to the shapes in `layers.py` , `models.py` and `training.py`, which can be found [here](https://github.com/fuyw/pyGAT).
> 
> Now I can run `train.py` as usual, but still only one gpu is used.
> 
> So I am confused how to use multiple gpus to run `pyGAT`.

HI！Is the problem you mentioned solved？
