### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by tanjia123456** [Diego999/pyGAT#50]
@Diego999 
hello, when i use this code to run my datasets, my data has 10242 nodes.
the error occurs:
RuntimeError: CUDA out of memory. Tried to allocate 6.25 GiB (GPU 0; 31.75 GiB total capacity; 25.01 GiB already allocated; 4.51 GiB free; 1.18 GiB cached)

do you know how to solve it?
Someone says reduce the batch-size, But  i haven't found any batch-size.

**Comment by huigoing** [comment]
Hi. I encounter the same question. do you solve?

**Comment by tanjia123456** [comment]
I'm so sorry,  now I use the tensorflow/GAT， maybe you can try the stupid way.

**Comment by abhigoku10** [comment]
@Diego999  @tanghui2017108  any update on this thread , i am also facing this issue @tanjia123456  where you able to solve this issue
