### ISSUE TITLE
The result score is  acc=84.6

### ISSUE THREAD

**Issue by FXiiX** [Diego999/pyGAT#68]
Why is the result of your code much better than that given in the paper。when paper's score is 83.7 and I get the score 84.6.Amazing

**Comment by wayc04** [comment]
I guess it might be due to the different frameworks used. Sometimes TensorFlow performs better than PyTorch, and sometimes it's the other way around.

> Why is the result of your code much better than that given in the paper。when paper's score is 83.7 and I get the score 84.6.Amazing
