### ISSUE TITLE
Installation version issues: mkl-fft==1.0.4

### ISSUE THREAD

**Issue by derek-saal** [Diego999/pyGAT#9]
Steps to reproduce:

1. Clone repo; cd to repo
1. Create env
    1. conda create -n pyGAT python=3.5
    1. conda activate pyGAT
1. pip install -r requirements.txt

Error: 
`Collecting mkl-fft==1.0.4 (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement mkl-fft==1.0.4 (from -r requirements.txt (line 3)) (from versions: )
No matching distribution found for mkl-fft==1.0.4 (from -r requirements.txt (line 3))
`

**Comment by derek-saal** [comment]
It might be a typo. The [repo](https://github.com/IntelPython/mkl_fft) states mkl_fft as the installation name.

**Comment by diegoantognini** [comment]
Thank you for pointing out this issue. You are right, I don't know why these MKL libraries were needed, I computed again the requirements and should be fixed now.

**Comment by duplessisaa** [comment]
Did this solve your issue ??

I've got exactly the same issue
------------------------------------------
Collecting mkl_fft==1.0.10 (from -r requirements.txt (line 44))
  Could not find a version that satisfies the requirement mkl_fft==1.0.10 (from
-r requirements.txt (line 44)) (from versions: )
No matching distribution found for mkl_fft==1.0.10 (from -r requirements.txt (li
ne 44))
------------------------------------------

**Comment by Carlo-Carandang** [comment]
Hello. I have the same problem, even after changing the filename in requirements.txt from mkl-fft to mkl_fft:
`
Collecting mkl_fft==1.0.6 (from -r requirements.txt (line 52))
  Could not find a version that satisfies the requirement mkl_fft==1.0.6 (from -r requirements.txt (line 52)) (from versions: )
No matching distribution found for mkl_fft==1.0.6 (from -r requirements.txt (line 52))
`
Your help would be much appreciated.

**Comment by duplessisaa** [comment]
Hi  there, i just settled for `mkl-fft` and it will then automatically just install the latest version...could not crack the issue. But when installed this did not cause any issues. So my advice would be not to specify the installation version.

**Comment by Carlo-Carandang** [comment]
@duplessisaa thanks for sharing your solution. Unfortunately, it didn't work for me:
`
No matching distribution found for mkl-fft (from -r requirements.txt (line 52))
`

**Comment by duplessisaa** [comment]
That sucks...sorry...FYI here is my Docker image pip install requirements, just so you can see how I called it...

    $PIP_INSTALL \	
        numpy \
        scipy \
        pandas \
	pvlib==0.6.0 \
        cloudpickle \
	pickleshare \
        scikit-learn==0.20.0 \
	python-dateutil==2.7.5 \
        matplotlib \
	PyMySQL==0.9.2 \
	mkl-fft \
	mkl-random \
	windrose==1.6.5 \
        Cython \
	tables==3.4.4 \

**Comment by Carlo-Carandang** [comment]
@duplessisaa thank man. Workaround- I just basically had to manually copy the mkl_fft and mkl_random folders (along with their -info folders, mkl_fft-1.0.6-py3.6.egg-info and mkl_random-1.0.1-py3.6.egg-info) from the Anaconda environment that runs my app locally
`
C:\Users\carandangc\Anaconda3\envs\web_scraper\Lib\site-packages
`
then pasted the folders into the lib file where the requirements.txt loaded the files for my app
`
C:\Users\carandangc\Desktop\testscrape\lib
`
Voila...now I have it in my lib folder for the cloud environment. Funny...I built an app to automate workflow processes, and here I am doing manual labour, copying and pasting LOL.

**Comment by duplessisaa** [comment]
Awesome !! Good-luck with the APP !

**Comment by blalterman** [comment]
I'm now running into this problem on Travis as well w/ `mkl-fft`. Has anyone found a long-term resolution to it?

**Comment by Mahnaz54** [comment]
conda install -c intel mkl_fft

This may work for you as it did for me.

**Comment by y26805** [comment]
seems to be a Python version issue, as 3.7 is not yet supported.
according to this GitHub issue (https://github.com/IntelPython/mkl_fft/issues/26) in the official repo,
> Yes, only 2.7, 3.5, and 3.6 wheels are currently available it seems.

a request to add 3.7 wheels has been added in Feb 2019 (https://github.com/IntelPython/mkl_fft/issues/34) but no action yet it seems..

**Comment by Keerthana2701** [comment]
ERROR: Could not find a version that satisfies the requirement mkl-service==2.3.0 (from -r /tmp/build_92d7e5cf_/requirements.txt (line 36)) (from versions: none)
ERROR: No matching distribution found for mkl-service==2.3.0 (from -r /tmp/build_92d7e5cf_/requirements.txt (line 36))

Note: mkl-service 2.3.0 is already installed .
please help

**Comment by SanjoyPator1** [comment]
> ERROR: Could not find a version that satisfies the requirement mkl-service==2.3.0 (from -r /tmp/build_92d7e5cf_/requirements.txt (line 36)) (from versions: none)
> ERROR: No matching distribution found for mkl-service==2.3.0 (from -r /tmp/build_92d7e5cf_/requirements.txt (line 36))
> 
> Note: mkl-service 2.3.0 is already installed .
> please help

did you find the answer

**Comment by imashutoshjha** [comment]
also getting the same error

**Comment by briana-jin-zhang** [comment]
Getting the same error as well

**Comment by MuriloCrr** [comment]
Entrei no requeriments.txt e tirei a versão do mkl-fft e rodou normalmente...

**Comment by ignaciojvig** [comment]
Srsly, python is ridiculous with these dependencies. ffs

**Comment by ketangangal** [comment]
Getting this error can anyone help !

ERROR: Could not find a version that satisfies the requirement mkl-fft==1.3.0 (from -r /tmp/build_6a08ebd4/requirements.txt (line 14)) (from versions: none)
       ERROR: No matching distribution found for mkl-fft==1.3.0 (from -r /tmp/build_6a08ebd4/requirements.txt (line 14))
